{'name': 'Studio customizations',
 'version': 'saas~19.3.1.0',
 'category': 'Studio',
 'description': 'This module has been generated by Odoo Studio.\n'
                'It contains the apps created with Studio and the '
                'customizations of existing apps.',
 'author': 'Alvaro33',
 'depends': ['ai', 'fleet', 'web_grid', 'web_hierarchy', 'web_studio'],
 'data': ['data/ir_model_fields.xml',
          'data/ir_ui_view.xml',
          'data/ir_default.xml'],
 'demo': [],
 'license': 'OPL-1'}